apiVersion: v1
kind: Namespace
metadata:
  name: msa-otus-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-otus-pod # Base POD name
  namespace: msa-otus-system
spec:
  selector:
    matchLabels:
      app: msa-otus # Selector for POD name search.
  template:
    metadata:
      labels:
        app: msa-otus
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: msa-otus-api
        image: msa-otus-api-amd64
        imagePullPolicy: IfNotPresent
